### ISSUE TITLE
Undefined index: elementIds

### ISSUE THREAD

**Issue by joshuabaker** [putyourlightson/craft-blitz#216] opened 2020-04-29 18:30 UTC
I’m seeing an issue with Craft 3.4.17.1 (and a few versions ahead of that) when trying to create an edit a section. It’s a completely fresh install and there’s nothing much going on.

### To reproduce
Steps to reproduce the behaviour:
1. Create a Single section
2. Edit the entry type
3. Change the title format (e.g. enable it or disable it)
4. Save

This results in an exception: `Undefined index: elementIds`, which is coming from here...

https://github.com/putyourlightson/craft-blitz/blob/a0fcd17b170f7b9a6e51e52b101600aa7bcb9c82/src/services/RefreshCacheService.php#L210-L213

### Versions
- Plugin version: 3.6.3
- Craft version: 3.4.17.1

**Comment by bencroker** [comment] 2020-04-29 18:38
This is a duplicate of https://github.com/putyourlightson/craft-blitz/issues/215, for which the fix is coming very soon.

**Comment by joshuabaker** [comment] 2020-04-29 18:39
Sorry for the dupe.

**Closed as completed by bencroker** 2020-04-29 18:38 UTC
Labels: bug

**Comment by bencroker** [comment] 2020-04-29 18:40
No problem, just released 3.6.4 with the fix.
