### ISSUE TITLE
Can't connect to repository on 3.0.0-beta.1

### ISSUE THREAD

**Issue by jdsimcoe** [putyourlightson/craft-blitz#138] opened 2019-10-25 19:28 UTC
I'm on Blitz `3.0.0-beta.1` on I get this error when trying to connect to a repository:

![image](https://user-images.githubusercontent.com/275617/67598603-c5251000-f722-11e9-9d3b-fd8c68947308.png)

My Craft site located at `~/Sites/jdsimcoe` and my static site is located at `~/Sites/jdsimcoe-static`. I'm probably doing something wrong but could use some help sorting this out.

**Comment by putyourlightson** [comment] 2019-10-28 17:27
It sounds like either you don't have Git installed globally, or you have not set up the Git repository at `~/Sites/jdsimcoe-static`. I'm also not sure that path will work, you may want to test it with the full folder path, for example `/Users/me/Sites/jdsimcoe-static`.

Also FYI `3.0.0-beta.2` is already available.

**Comment by jdsimcoe** [comment] 2019-10-28 19:00
@putyourlightson I have Git installed globally at `/usr/local/bin/git` via Homebrew. I do have a valid Git repository at `/Users/jdsimcoe/Sites/jdsimcoe-static/`. It has a valid Git URL and `.git/config` all setup

![image](https://user-images.githubusercontent.com/275617/67708735-e59ad780-f979-11e9-82b7-5a28c137f03d.png)

Here is the contents of the `.git/config` for the repo:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:jdsimcoe/jdsimcoe-static.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
The repo is located here: https://github.com/jdsimcoe/jdsimcoe-static.

**Comment by putyourlightson** [comment] 2019-10-28 19:53
Does the following work in the console?
```
cd /Users/jdsimcoe/Sites/jdsimcoe-static

git fetch
```

**Comment by jdsimcoe** [comment] 2019-10-28 19:54
@putyourlightson I ran `git fetch` and it didn't error out, but there was no output:

```sh
~/Sites/jdsimcoe-static master
❯ git fetch

~/Sites/jdsimcoe-static master
❯ 
```

Also the `cd /Users/jdsimcoe/Sites/jdsimcoe-static` worked and navigated to `~/Sites/jdsimcoe-static`.

**Comment by putyourlightson** [comment] 2019-10-28 20:23
That is the expected behaviour. It seems though that the Git binary is not being found. Can you try manually changing [this line](https://github.com/putyourlightson/craft-blitz/blob/3.0.0-beta.2/src/drivers/deployers/GitDeployer.php#L199) to the following:
```
$gitWrapper = new GitWrapper('/usr/local/bin/git');
```

**Comment by jdsimcoe** [comment] 2019-10-28 20:26
@putyourlightson I just modified that file and it returns the same error:

`Plugin settings saved. One or more deployer connections failed.` with the same `Error for “jdsimcoe”: Unable to find the Git executable.` error below.

**Comment by putyourlightson** [comment] 2019-10-28 20:30
Is there anything worth noting in `storage/logs/blitz.log`?

**Comment by jdsimcoe** [comment] 2019-10-28 20:34
There is no `storage/logs/blitz.log` file. Maybe that is an issue?

**Comment by putyourlightson** [comment] 2019-10-28 20:49
That just means that no errors have been logged. Can you change [this line](https://github.com/putyourlightson/craft-blitz/blob/3.0.0-beta.2/src/drivers/deployers/GitDeployer.php#L245) instead? I marked the wrong line in my previous comment.

**Comment by jdsimcoe** [comment] 2019-10-28 22:33
@putyourlightson I updated that line and now I get this error:

`Error for “jdsimcoe”: fatal: unable to access 'https://git@github.com:jdsimcoe/jdsimcoe-static.git/': URL using bad/illegal format or missing URL`

I'm assuming this is because I use SSH Git URLs. I adjusted the URL to the https one `https://github.com/jdsimcoe/jdsimcoe-static` and was able to save the Deployment settings succesfully!!! 👍

However, I still get these weird `Failed` errors when trying to save my Homepage entry:

![image](https://user-images.githubusercontent.com/275617/67723102-3faa9580-f998-11e9-9c35-944108a841c1.png)

Still no Blitz log files to check to see what those Failed errors are.

**Comment by putyourlightson** [comment] 2019-10-28 22:43
Is there anything in the `title` tag when you hover over the "Failed" label?

For example: https://twitter.com/ben_pylo/status/1181940037954494464

**Comment by jdsimcoe** [comment] 2019-10-28 22:49
@putyourlightson this is what I see:

<img width="229" alt="Screen Shot 2019-10-28 at 3 48 42 PM" src="https://user-images.githubusercontent.com/275617/67723862-813c4000-f99a-11e9-97c3-76f8083eb030.png">

**Comment by jdsimcoe** [comment] 2019-10-28 22:53
@putyourlightson Actually when I dig into the title attribute I see this:

`Unknown component ID: deployUrisWithProgress`

**Comment by putyourlightson** [comment] 2019-10-29 10:52
Can you try the fix in `3.0.0-beta.2.1`?

```
composer update putyourlightson/craft-blitz
```

**Comment by jdsimcoe** [comment] 2019-10-30 17:20
@putyourlightson I updated to that version but still had to add `$gitWrapper = new GitWrapper('/usr/local/bin/git');` in both places in the `Deployer` file to get errors to go away. I got a successfully "Deploy successful" message but nothing was added to my local or remote `jdsimcoe-static` repo.

**Comment by putyourlightson** [comment] 2019-10-30 20:24
It sounds like maybe `/usr/local/bin/git` is not considered globally installed by GitWrapper (which uses `symfony/process` under the hood).

That's a good start, have you tried refreshing the cache using the utility? Are the cache files being rewritten to the cache folder?

**Comment by putyourlightson** [comment] 2019-11-05 12:47
Added a fix in version `3.0.0-beta.3` which should be able to locate Git on your server.

Have you managed to get deploying to work? Please ensure that at least one of your pages is cached.

**Comment by jdsimcoe** [comment] 2019-11-15 23:16
@bencroker @putyourlightson I'll give this another go. Haven't been able to get Git deploying to work yet.

**Comment by bencroker** [comment] 2019-11-15 23:49
Can you please try with the current `3.0.0-RC1` version?

**Comment by jdsimcoe** [comment] 2019-11-16 22:23
Hi @bencroker I updated to `3.0.0-RC1` and I now get this:

![image](https://user-images.githubusercontent.com/275617/68999888-07ea8b80-087c-11ea-8477-0b8fbe4913ee.png)

It's not the same `Git executable` error at least.

**Comment by bencroker** [comment] 2019-11-16 23:07
Yup, we've made some progress :)

Can you check the `jdsimcoe-static/.git/config` file to ensure that the `origin` remote URL is correct? It should be of the form:
```
https://<personal access token>@github.com/<username>/<repository name>
```

**Comment by bencroker** [comment] 2019-11-17 10:21
Can you please try again with RC2:
```
composer require putyourlightson/craft-blitz:^3.0.0-RC2
```

**Comment by jdsimcoe** [comment] 2019-11-18 17:14
@bencroker So I updated the URL in `.git/config` to include the access token and I updated to `RC21. How I'm getting this error again:

![image](https://user-images.githubusercontent.com/275617/69074194-c2e16900-09e3-11ea-825a-82596d240045.png)

**Comment by bencroker** [comment] 2019-11-18 19:17
Strange. What does running the command `which git` output on the server?

**Comment by jdsimcoe** [comment] 2019-11-18 19:23
```sh
❯ which git
/usr/local/bin/git
```

**Comment by bencroker** [comment] 2019-11-19 08:30
Can you please double check that you are running 3.0.0-RC2 by looking in _Settings > Plugins_?

**Comment by jdsimcoe** [comment] 2019-11-19 18:13
I am running `3.0.0-RC2`:

![image](https://user-images.githubusercontent.com/275617/69173720-2f786880-0ab5-11ea-9344-d40fbfa63039.png)

**Comment by jdsimcoe** [comment] 2019-11-19 20:42
Also @bencroker when I manually go to `GitDeployer.php` and edit line 313 to this...

`$gitWrapper = new GitWrapper('/usr/local/bin/git');`

...the error goes away. The GUI shows when I re-save my Home page entry that `Deploying files` task is successful. However, I see nothing in `/public/cache/blitz` or the repo I have connected.

**Comment by bencroker** [comment] 2019-11-19 22:19
I'm considering adding a config override for the Git path but that's really strange because it should use the value of `which git` if one exists.

So is warming the cache not working either? What kind of local setup do you have and have you tested this anywhere else?

**Comment by jdsimcoe** [comment] 2019-11-21 19:08
Yeah @bencroker it is really strange! So I disabled Git Deployment for now and I can’t even get Blitz it save cache locally on my Craft site on my local machine. I’m wondering if I haven’t configured something right. I’ll admit I’m new to using Blitz.

**Comment by bencroker** [comment] 2019-11-21 20:09
What kind of local setup do you have?

**Comment by jdsimcoe** [comment] 2019-11-21 20:10
Just running a local Laravel Valet setup with `mysql@5.7`.

**Comment by bencroker** [comment] 2019-11-21 20:15
Check the scenarios documented here, which usually explain why pages are not being cached.
https://putyourlightson.com/plugins/blitz#common-issues

**Comment by jdsimcoe** [comment] 2019-11-21 20:27
Ah! Thanks @bencroker. I had the debug toolbar on because I was troubleshooting the Blitz deploy connection errors. Ok, so that worked!

The only remaining thing is the weird `$gitPath` issue I encountered in lines 309-313 of `GitDeployer.php`:

```sh
$process = new Process(['which', 'git']);
$process->run();
$gitPath = trim($process->getOutput()) ?: null;

$gitWrapper = new GitWrapper('/usr/local/bin/git');
```
I got things working by manually added my `which git` location but for whatever reason the `run()` or `trim()` must have borked something in my setup.

**Comment by bencroker** [comment] 2019-11-21 20:35
Can you try a cheap and dirty dump to help us see what the value actually is?
```
$process = new Process(['which', 'git']);
$process->run();
$gitPath = trim($process->getOutput()) ?: null;

Craft::dd($gitPath);
```

If that doesn't reveal anything then can you please attach the main project `composer.lock` file here (or send to info@putyourlightson.net)?

**Comment by jdsimcoe** [comment] 2019-11-21 20:48
@bencroker The output with that code is: `null`:

![image](https://user-images.githubusercontent.com/275617/69375423-25916980-0c5d-11ea-9677-70105ec731aa.png)

I'll send you my `composer.lock` to the email above.

**Comment by bencroker** [comment] 2019-12-02 17:15
Jonathan, I'm still unable to replicate this and suspect it may have to do with your local development environment. Can you please try doing what the answer here describes to get Git working globally?
https://superuser.com/questions/593352/how-do-i-get-homebrew-to-recognize-my-git-install

**Comment by jdsimcoe** [comment] 2019-12-02 17:41
@bencroker I have Brew install normally with Git. Homebrew recognizes Git and has been installed this way on two machines. I have a vanilla Homebrew + Laravel Valet install and can reproduce this on two machines that have Git installed successfully via Homebrew. I read the article and followed instructions but it didn't apply since my Homebrew Git is already installed and working.

**Comment by jdsimcoe** [comment] 2019-12-02 17:43
Also `which git` has always returned `/usr/local/bin/git`. When I manually do this `$gitWrapper = new GitWrapper('/usr/local/bin/git');` it works perfectly. It's just something in this command that isn't outputting my path correctly:

```php
$process = new Process(['which', 'git']);
$process->run();
$gitPath = trim($process->getOutput()) ?: null;
```

**Comment by bencroker** [comment] 2019-12-02 19:45
Can you please try with this?
```php
$process = new Process(['which', 'git']);
$process->mustRun();
Craft::dd(trim($process->getOutput()));
```

**Comment by jdsimcoe** [comment] 2019-12-02 19:49
Ok @bencroker now, we're getting somewhere. I get this error in the Debug toolbar:

```
Symfony\Component\Process\Exception\ProcessFailedException: The command "'which' 'git'" failed.
Exit Code: 1(General error)
Working directory: /Users/jdsimcoe/Sites/jdsimcoe/public
```

**Comment by bencroker** [comment] 2019-12-02 19:59
Ok so this is quite confusing. According to your `composer.lock` file, you have `symfony/process` v3.3.6 installed. I tested locally using the exact same version and the `which git` command works fine for me. 

If you have PHP 7.1.3 or above then you should be able to install a much more recent version of `symfony/process`. Can you check what version of PHP is actually installed and what version is in the `composer.json` file?

**Comment by jdsimcoe** [comment] 2019-12-02 21:15
I upgraded `symfony/process` to v4.4.1 and I set php to 7.4 which I'm on locally. Here is composer.json:

```json
{
  "require": {
    "clubstudioltd/craft-asset-rev": "6.0.2",
    "craftcms/cms": "3.3.16.1",
    "nystudio107/craft-typogrify": "1.1.18",
    "putyourlightson/craft-blitz": "^3.0.0-RC2",
    "symfony/process": "^4.4.1",
    "vlucas/phpdotenv": "^3.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.4"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

It still returns this error for me:

```
Symfony\Component\Process\Exception\ProcessFailedException: The command "'which' 'git'" failed.
```

**Comment by jdsimcoe** [comment] 2019-12-02 21:27
@bencroker After more digging I `symfony/process` fails running any `which` command. I tried running `which php` and even just `which` and it fails every time. I tried running an `ls` command through process and it does work successfully.

**Comment by bencroker** [comment] 2019-12-02 21:57
Ok so it seems that `which` is not in the `$PATH` for the user that is being used on the web server.

Can you try this?
```
$process = new Process(['/usr/bin/which', 'git']);
```

And to check the user:
```
$process = new Process(['id', '-un']);
```

The fix may end up being to add the `which` command to the `$PATH`, usually in `/usr/bin`.

**Comment by jdsimcoe** [comment] 2019-12-02 21:57
@bencroker I did some deep digging into terminal/shell commands and found the root command that `which git`, `where git` or `type git` is doing under the surface. The commmand is `command -v git` (the lowercase **v** is important).

Adjusted, this now works for me (lines 379–384):

```php
// Find the git binary
$process = new Process(['command', '-v', 'git']);
$process->run();
$gitPath = trim($process->getOutput()) ?: null;

$gitWrapper = new GitWrapper($gitPath);
```

Here are the articles that helped me dig into the `which` and `type` commands:

- https://en.wikipedia.org/wiki/Which_(command)
- https://en.wikipedia.org/wiki/Type_(Unix) (this article references the `command` builtin that worked in my setup)

I still have no idea why `which` and `where` both fail for me using `symfony/process`.

**Comment by jdsimcoe** [comment] 2019-12-02 23:08
@bencroker would you still like me to try your proposed solution or do you plan to test my `command -v git` solution above? I've tested `command -v git` on both macOS and Linux and it seems to work flawlessly as a bulletproof replacement for `which git`.

**Comment by bencroker** [comment] 2019-12-02 23:12
Thanks @jdsimcoe, `command -v git` is looking very promising so I probably will switch to it, thank you for your digging! If you wouldn't mind testing what I proposed as I'd like to put this issue to bed and understanding what the root cause is would help me :)

**Comment by jdsimcoe** [comment] 2019-12-02 23:19
Ok @bencroker so this line failed for me:

```
$process = new Process(['/usr/bin/which', 'git']);
```

It produced the identical error output as `which git`.

When I run `$process = new Process(['id', '-un']);` it outputs this: `'jdsimcoe'`. Hope that helps!

**Comment by bencroker** [comment] 2019-12-02 23:20
Ok thanks. I'll switch to `command -v git` and we can close this out. Thanks again for your help!

**Comment by jdsimcoe** [comment] 2019-12-02 23:21
Glad to help! Thanks for your patience for all the work on Blitz 3. Can't wait to use it in my project.

**Closed as completed by bencroker** 2019-12-02 23:20 UTC
