### ISSUE TITLE
Previous URI Patterns not working (locales no longer used)

### ISSUE THREAD

**Issue by roberttolton** [putyourlightson/craft-blitz#39] opened 2018-11-16 20:59 UTC
Hi,

After updating to the latest version, the URI Patterns I was using before no longer work:

```
^/en/posts
^/ja/posts
^/en/$
^/ja/$
```

I previously had to include the locale in the URI to get it to cache. Now, it only caches with:

```
^posts
```

Which is fine, but Blitz now no longer caches my homepage. What should the URI Pattern be for a URL such as `example.com/en` when the `en` is no longer a matchable element in the pattern?

EDIT: I found that `^$` works for caching the homepage.

It also required me to remove the slashes at the beginning.

Since the locale is now missing from the URI patterns, it's also meaning that my scripts for redirecting `.com/posts/one` to `.com/en/posts/one` aren't working, because for the URL `.com/posts/one` Blitz is serving up (itself, not NGINX) the cached HTML of `.com/en/posts/one`. I need `.com/posts/one` to be _uncached_ because I have to do some logic.

**Comment by roberttolton** [comment] 2018-11-16 21:38
The update also appears to have broken pagination, as `.com/en/posts/p4` is served by Blitz with the same HTML file as `.com/en/posts/p1`.

**Comment by putyourlightson** [comment] 2018-11-16 21:51
Ok, thanks for reporting this, it is due to an unprecedented affect of a recent release that fixed another issue. We'll issue a fix for this over the weekend.

**Comment by putyourlightson** [comment] 2018-11-16 22:03
Am I correct in assuming that you have 2 sites, one for `en` and one for `ja`?

**Comment by roberttolton** [comment] 2018-11-17 14:49
I have three, `en` is default alongside `ja` and `zh` (I didn't include all patterns above for brevity).

`en` is the site where I'm specifying to Craft that the URL ends with `.com/en`.

**Comment by putyourlightson** [comment] 2018-11-17 19:11
Ok thanks, it seems that the issue is running multi-site with the same host name for all 3 sites. We will release an update early next week adding better multi-site functionality that will resolve this as well as the pagination issue you mentioned above. 

In the meantime, if you need to then you can downgrade to 1.6.7 as follows:

    composer require putyourlightson/craft-blitz:1.6.7

Thanks for your understanding!

**Comment by roberttolton** [comment] 2018-11-18 15:46
Ok, thanks for the update!

**Comment by Tam** [comment] 2018-11-19 14:53
+1 for the pagination issue. Blitz appears to be ignoring the pagination segment completely.

**Comment by putyourlightson** [comment] 2018-11-19 16:39
Fixed in the pagination issues in 1.6.9 and 1.7 will follow this week with better multi-site support.

**Comment by putyourlightson** [comment] 2018-11-20 19:53
Added multi-site support in 1.7.0.

**Closed as completed by putyourlightson** 2018-11-20 19:53 UTC

**Comment by roberttolton** [comment] 2018-12-03 02:26
Thanks for the update @putyourlightson , though what's the correct URI pattern to match all my sites homepages? Given that each of my homepages are served as `.com/en` `.com/ja` `.com/zh` and these site / locale slugs are no longer used in URI matching, essentially the only way I see of matching a homepage request is `^$` essentially saying an empty string..? Which I've tried, and no longer seems to work.

**Comment by putyourlightson** [comment] 2018-12-03 07:08
Just `/` should work to match the homepage.

**Comment by roberttolton** [comment] 2018-12-03 08:36
Thanks, that does cache it, but not in a way that NGINX can then serve.

Other rules create folders like so:
`/cache/en/posts/post-one/index.html`

With `/` as a rule, the following folder is created:
`/cache/en/https:/website.com/en/index.html`

Please note it is not a mistake that there is only one `/` after the `https:` above. It's actually these folders: `https:` `website.com` `en`

**Comment by putyourlightson** [comment] 2018-12-03 09:20
Is this with the latest version 1.8.0 of Blitz?

**Comment by Djive** [comment] 2018-12-03 10:48
Just to chip in with my experience testing this.

We have 1 main site (lets call it "site1") and many additional sites (site2, site3, ...) setup as addon domains. 
Putting `/` created folder "https" in main site and in that folder other folders like "mail.site2.com", "mail.site3.com", "site2.site1.com", "site3.site1.com", "site2.com", "site3.com"...
Along with "https" folder, on that same level it also created folders for each of the additional sites normally.

We had to block 1 site from caching and we wanted to start with only homepage, so we put `/` in the Excluded URI Patterns for that site. This resulted in entire site not being cached anymore. We visited every page on the site but nothing got cached anymore.

Also, can confirm that `^$` does cache homepage.

Hope this was of some help.

Blitz 1.8.0
Craft Pro 3.0.33

**Comment by putyourlightson** [comment] 2018-12-03 11:50
Thank you for correcting me @Djive, in the latest version of Blitz, the correct pattern for the homepage is indeed `^$`.

**Comment by roberttolton** [comment] 2018-12-04 00:03
Unfortunately for me, with the latest version of Blitz, `^$` does not cache the homepage of any of my sites..

Any information I can dig up to help?

**Comment by putyourlightson** [comment] 2018-12-04 07:25
I can take a look if you send login credentials and the steps to see the issue to info@putyourlightson.net.
