### ISSUE TITLE
Entry edits causing site to render/route to index

### ISSUE THREAD

**Issue by wihodges** [putyourlightson/craft-blitz#344] opened 2021-09-09 18:36 UTC
### Describe the bug
When user edits an entry, the site including the backend admin portal are all redirected to index page. The issue is solved once ./craft clear-caches/blitz is run. 

I'm still very unclear on what/how this is happening. I have Blitz on a couple other sites with no issues, although those aren't fully updated.

### To reproduce
Steps to reproduce the behaviour:
1. Edit and entry
2. Save

### Expected behaviour
N/A

### Screenshots
I noticed this generated in the blitz cache file store:
"index.ph%70"
<img width="323" alt="Screen Shot 2021-09-09 at 1 23 26 PM" src="https://user-images.githubusercontent.com/286956/132743001-6f34cda3-7c9f-4696-840f-e3aab385df19.png">
I checked other sites with blitz and all I see is index.html - not duplicate index.php folders.

### Versions
- Plugin version: 3.10.3
- Craft version:  3.7.12

**Comment by wihodges** [comment] 2021-09-09 19:06
Ok can confirm that it's these errant index.php folders that are causing the issue. Once they are deleted, site returns back to normal. What I'm confused by is why/how they are getting generated.

**Comment by wihodges** [comment] 2021-09-09 20:41
Alright I found a temporary workaround by adding 'index.php' and 'index.ph%70' into exclude URI parameters. This seems to do the trick, but a little worriesome as to why this is happening all of the sudden. Any ideas? I'm assuming there maybe something specific in my install that is causing the issue and probably not a global bug. 

<img width="983" alt="Screen Shot 2021-09-09 at 3 40 43 PM" src="https://user-images.githubusercontent.com/286956/132759667-a6301341-d237-4464-a887-3ca46670783f.png">

**Comment by wihodges** [comment] 2021-09-09 22:04
Ok another update. Appears that when I disable SEOmatic, blitz doesn't generate those errant index.php folder/files.  Not sure where the issue lies.

**Comment by bencroker** [comment] 2021-09-10 06:05
Great detective work! I’ll see if I can replicate the issue with and without SEOmatic, but it sounds like it may be causing those URLs to be cached when they normally should not be, although I can’t think of why.

**Comment by bencroker** [comment] 2021-09-13 07:43
This appears to be caused by a combination of Blitz not URL decoding the request before checking if it contains `index.php` (which it already does) and server configuration. I'm going to address the root cause, which is a bigger job, but should also resolve this issue. Thanks for reporting it!

**Comment by wihodges** [comment] 2021-09-13 18:01
Awesome great to hear. Oddly again, when I went to test again in a new cloned server environment, I couldn't get it to fail again once I removed the ignore index.php hack so definitely seems like a really an odd edge case.

**Comment by bencroker** [comment] 2021-09-14 20:17
Yes, for sure, but it's good that you reported it so we can ensure that this edge case is prevented in future versions!

**Comment by bencroker** [comment] 2021-10-18 09:20
Released in version 3.10.4.

**Closed as completed by bencroker** 2021-10-18 09:20 UTC
Labels: bug
