### ISSUE TITLE
Excluded Uri Patterns are not working

### ISSUE THREAD

**Issue by OneX** [putyourlightson/craft-blitz#309] opened 2021-04-21 19:19 UTC
### Describe the bug
I have multi-site configuration.

And i am trying excluding couple pages on those multi site.

For default page i used this excluded uri pattern, which worked:

` [
    'siteId' => 1,
    'uriPattern' => 'user/.*'
],`

But for second site i used this pattern, which did not worked:

`[
  'siteId' => '2',
  'uriPattern' => 'usuario/.*'
],`

Not working pattern will work if i don't use siteId, like this

`[
  'siteId' => '',
  'uriPattern' => 'usuario/.*'
],`

### Expected behaviour
Pages that have 'usuario/.*' as part of uri would not get cached

### Versions
- Plugin version: 3.8.0
- Craft version: 3.6.12

**Comment by bencroker** [comment] 2021-04-22 08:01
Can you show me the base site URLs for site 1 and 2?

**Comment by OneX** [comment] 2021-04-22 09:28
Here you are:

Site 1:  https://www.goodsoil.com/
Site 2: https://www.goodsoil.com/es/

Maybe this would help to debug.

In my config/general.php i set site urls like this:

`'siteUrl' => [
  'en_us' => getenv('SITE_URL'),
  'es' => '@baseSiteUrl/es',
],`

And this is alias i use for second site:

`'@baseSiteUrl' => getenv('SITE_URL'),`

**Comment by bencroker** [comment] 2021-04-22 18:38
Thank you. I suspect the issue is to do with how Blitz detects which site the page being viewed is in. Since the base URL of site 1 is a substring of the base URL of site 2, Blitz assumes that the page at `https://www.goodsoil.com/es/usuario/xyz`is in the default site. I'll need to test locally and confirm, but will let you know as soon as I have an update.

**Comment by bencroker** [comment] 2021-04-22 20:09
This should hopefully be fixed in https://github.com/putyourlightson/craft-blitz/commit/50a7840440c3ac28b6e1790397f2d4812247bceb. You can either test locally now or wait for the next release.

**Comment by OneX** [comment] 2021-04-23 11:10
@bencroker thanks!

**Comment by bencroker** [comment] 2021-05-03 09:21
Released in version 3.9.0.

**Closed as completed** 2021-05-12 08:22 UTC
Labels: bug
