### ISSUE TITLE
IncludeCached function loading wrong component

### ISSUE THREAD

**Issue by jevans1808** [putyourlightson/craft-blitz#534] opened 2023-07-14 10:18 UTC
Unsure exactly of what caused this to start happened. I believe the blitz cache was cleared, and upon being refreshed, it appeared to not be injecting the correct templates.

Below is the snippet being used, and component-1 was being overwritten with the contents of component-2. 

```
<section id="component-1">
{{ craft.blitz.includeCached('/dynamic/component-1') }}
</section>

<section id="component-2>
{{ craft.blitz.includeCached('/dynamic/component-2') }}
</section>
```

Hopefully that makes sense, I'd like to give more info, but this is all I really have to go off of.

**Comment by bencroker** [comment] 2023-07-14 11:32
Please retest after refreshing the cache and provide the Blitz and Craft version numbers you're running (ideally the latest to exclude the possibility of the issue already having been fixed).

**Comment by bencroker** [comment] 2023-07-19 09:45
I cannot reproduce this locally. Please update to the latest version of Blitz, refresh the cache and retest.

**Comment by jevans1808** [comment] 2023-07-24 10:12
Thanks Ben, the issue seems to have disappeared.  I've updated Craft and Blitz to the latest version anyway, but I'm still unsure what caused this issue. Thanks anyway.

**Comment by jevans1808** [comment] 2023-09-11 07:36
Hi Ben,

Sorry to reopen this, but I've had the issue occur several more times over the past couple weeks. I've got a bit more information this time round though, but I'm still unsure what is the actual cause.

I am running Craft 4.4.16.1 and Blitz 4.5.2.

I have noticed that on the odd occasion, an index.html is being added to /cache/blitz/_includes.  This always contains the code for 1 of the includes, and is then, from what I can tell, causing all includes to use that component, regardless of their index. 

Apologies if this is some sort of misconfiguration on my part, but I can't see anything that would cause this on my end. Any help would be greatly appreciated, but as mentioned, I can't tell what is causing this index.html to be created.

**Comment by bencroker** [comment] 2023-09-11 16:10
If you delete the `/cache/blitz/_includes/index.html` file and then visit `domain.com/_includes`, do you get a 404 page not found error, as expected?

**Comment by jevans1808** [comment] 2023-09-11 16:11
I do, yes.

**Comment by bencroker** [comment] 2023-09-11 16:22
Hmm, in that case there’s no apparent reason why Blitz would ever create that `index.php` file. Do you have SSI enabled in the advanced plugin settings?

**Comment by jevans1808** [comment] 2023-09-11 16:23
Yea, I've been wracking my brains as to why it would even try to create the index file. Whats weirder is the index file is just the contents of 1 of the includes.

SSI is disabled as it it not detected on the server.

**Comment by bencroker** [comment] 2023-09-11 17:05
> SSI is disabled as it it not detected on the server.

Ok, can you confirm that the `includeCached` tag is outputting `script` tags which then make AJAX requests to the server?

**Comment by jevans1808** [comment] 2023-09-11 17:09
I can confirm that the elements being rendered like this:

```
<span id="blitz-inject-1" class="blitz-inject blitz-inject--injected" data-blitz-id="1" data-blitz-uri="/_includes" data-blitz-params="action=blitz%2Finclude%2Fcached&amp;index=2730909493" data-blitz-property="">
 ---- components code here ----
</span>
```

with a GET request to the below URL path:
/_includes?action=blitz%2Finclude%2Fcached&index=2730909493

The index seen in these 2 snippets also lines up correctly with what the component should be according to the Datebase.

**Comment by bencroker** [comment] 2023-09-11 17:50
I’m struggling to come up with a sound explanation for what might be happening here. Can you see if SSI can be enabled on the server using one of the methods as described in https://putyourlightson.com/plugins/blitz#ssi-enabled? That is anyway a much more performant way of using cached includes.

**Comment by jevans1808** [comment] 2023-09-12 07:35
I'll try and get that enabled.

In the meantime, I'll keep an eye out for when it happens again and take a note of the time and compare that to any sort of notable server events like a restart or something, in case that helps shed any light.

**Comment by bencroker** [comment] 2023-09-12 08:30
Great, that would be helpful. I’ll close this issue for now but can reopen if the problem resurfaces again.

**Closed as completed by bencroker** 2023-09-12 08:30 UTC
Labels: bug
