### ISSUE TITLE
"Site not found" error on Blitz Settings page

### ISSUE THREAD

**Issue by louderthan10** [putyourlightson/craft-blitz#192] opened 2020-03-26 19:59 UTC
Hi Ben!

### Describe the bug
I just noticed that I'm getting a "Site not found" error when I go to the Blitz settings page in the CMS. I checked this after updating to 3.5.2 because of the warning in the latest release, but it's also occurring in 3.5.0. 

Possibly important detail: It is on a multi-site, and one of the sites has been deleted since installing Blitz (there are three still there). 

### To reproduce
Steps to reproduce the behaviour:
1. Go to "/admin/settings/plugins/blitz"
2. See error message "Site not found – craft\errors\SiteNotFoundException
Site with UID ”XXXXX“ not found!"

### Expected behaviour
See the Blitz settings page

### Versions
- Plugin version: 3.5.2 (and 3.5.0)
- Craft version: 3.4.10.1 (and 3.4.9)

**Comment by bencroker** [comment] 2020-03-26 20:14
Thanks Travis, I just tested this locally by deleting a site and cannot reproduce the error. Do you perhaps have the old site ID or UID in the `blitz.php` config file? If not then can you please check the logs for the stack trace and exact origin of the error?

**Comment by louderthan10** [comment] 2020-03-26 21:30
Looks like it may be tied to the Cloudflare purger. 

I have my Cloudflare global API set in my config and that looks correct.

I don't have my zone ID set in the config file, but it also appears to be correct in these errors (last 3 from today). Looks like they started on Feb 2.

![blitz-error](https://user-images.githubusercontent.com/49751/77698343-b2cb2e80-6f6d-11ea-973f-1bbf764f3c9a.png)

Here's a stack trace from my local install with the latest version: 

```
craft\errors\SiteNotFoundException: Site with UID ”XXXXXXXXX“ not found! in /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/services/Sites.php:407
Stack trace:
#0 /Users/trav/Websites/louderthanten/vendor/putyourlightson/craft-blitz/src/drivers/purgers/CloudflarePurger.php(145): craft\services\Sites->getSiteByUid('XXXXXXXXX...')
#1 /Users/trav/Websites/louderthanten/vendor/putyourlightson/craft-blitz/src/controllers/SettingsController.php(79): putyourlightson\blitz\drivers\purgers\CloudflarePurger->test()
#2 [internal function]: putyourlightson\blitz\controllers\SettingsController->actionEdit()
#3 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit', Array)
#6 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit', Array)
#7 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('blitz/settings/...', Array)
#8 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('blitz/settings/...', Array)
#9 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /Users/trav/Websites/louderthanten/public/index.php(21): yii\base\Application->run()
#12 /Users/trav/.composer/vendor/laravel/valet/server.php(158): require('/Users/trav/Web...')
#13 {main}
```

**Comment by bencroker** [comment] 2020-03-27 08:02
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/739c37fd9d11320571672471196c28ac1f6986d0.

**Closed as completed by bencroker** 2020-03-27 08:02 UTC
Labels: bug
