### ISSUE TITLE
Missing ID triggers 2K+ in 24h

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-blitz#674] opened 2024-06-18 10:08 UTC
### Bug Report

We have a setup with Blitz + Craft 4 + Clouddfront which means we pay for invalidation requests. The last 24h we've had `
2,534`  invalidation requests for an ID that doesn't seem to exist in the DB and has no elements attached to it:
`Blitz cache refresh job added : {"cacheIds":{"5585":true},"elements":[]} `

We have a DB entry for `5584`and `5586` but not for `5585`.

#### Application Info

- PHP version: 8.1.17
- Craft edition & version: Pro 4.9.7
- Database driver & version: MySQL 8.0.26

#### Installed Plugins

- Blitz: 4.18.1
- Blitz CloudFront Purger: 4.0.0
- CKEditor: 3.8.3
- Cloner: 2.0.4
- Control Panel CSS: 2.6.0
- Dashboard Begone: 2.0.0
- Feed Me: 5.5.0
- Field Manager: 3.0.8
- Google Cloud Storage: 2.2.0
- Hyper: 1.1.31
- Imager X: 4.4.0
- Inventory: 3.2.0
- Jason: 3.0.1
- Knock Knock: 2.0.11
- MatrixMate: 2.2.1
- Navigation: 2.0.27
- Retour: 4.1.16
- SendGrid: 2.0.1
- SEOmatic: 4.0.49
- Sprig: 2.8.1
- Super Table: 3.0.14
- Template Selector: 5.0.1
- Translations: 4.0.2
- Vite: 4.0.9
- Vizy: 2.1.19

#### Loaded Modules

- twig-extension: modules\sitemodule\Module
- blitz-refresh-cache-logger: modules\BlitzRefreshCacheLogger
- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base
- debug: craft\debug\Module

#### Blitz Plugin Settings

```json
{
    "debug": true,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 2,
    "includedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": ".*"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\YiiCacheStorage",
    "cacheStorageSettings": [],
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitzcloudfront\\CloudFrontPurger",
    "cachePurgerSettings": {
        "apiKey": "********************",
        "apiSecret": "****************************************",
        "distributionId": "E35TL05JGJ1ANJ",
        "condenseUrls": false
    },
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": true,
    "ssiTagFormat": "[an error occurred while processing the directive]",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 2,
    "includedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": "gclid"
        },
        {
            "siteId": "",
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": false,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-cache, no-store, must-revalidate",
    "cacheControlHeader": "public, s-maxage=2592000, max-age=2592000",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 3600,
    "maxRetryAttempts": 2,
    "maxUriLength": 255,
    "mutexTimeout": 30,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ The Blitz Hints utility is reporting 22 eager-loading opportunities.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ No globals exist.
- ✅ The @web alias is explicitly defined.
- ✅ Queue jobs are configured not to run automatically via web requests.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking [#1]

- Tracked Pages: 242
- Tracked Includes: 27
- Tracked Query String Params: 0
- Tracked Elements: 982
    - craft\elements\Entry: 517
    - craft\elements\Asset: 391
    - verbb\navigation\elements\Node: 74
- Tracked Element Queries: 282
    - craft\elements\Entry: 267
    - verbb\navigation\elements\Node: 15
- Tracked Tags: 0

#### Site Tracking [#2]

- Tracked Pages: 228
- Tracked Includes: 19
- Tracked Query String Params: 0
- Tracked Elements: 978
    - craft\elements\Entry: 477
    - craft\elements\Asset: 441
    - verbb\navigation\elements\Node: 60
- Tracked Element Queries: 325
    - craft\elements\Entry: 312
    - verbb\navigation\elements\Node: 13
- Tracked Tags: 0

#### Site Tracking [#3]

- Tracked Pages: 449
- Tracked Includes: 27
- Tracked Query String Params: 0
- Tracked Elements: 1383
    - craft\elements\Entry: 682
    - craft\elements\Asset: 624
    - verbb\navigation\elements\Node: 77
- Tracked Element Queries: 553
    - craft\elements\Entry: 538
    - verbb\navigation\elements\Node: 15
- Tracked Tags: 0

#### Site Tracking [#4]

- Tracked Pages: 398
- Tracked Includes: 25
- Tracked Query String Params: 0
- Tracked Elements: 1307
    - craft\elements\Entry: 666
    - craft\elements\Asset: 563
    - verbb\navigation\elements\Node: 78
- Tracked Element Queries: 481
    - craft\elements\Entry: 464
    - verbb\navigation\elements\Node: 17
- Tracked Tags: 0

#### Site Tracking [#5]

- Tracked Pages: 242
- Tracked Includes: 22
- Tracked Query String Params: 0
- Tracked Elements: 1015
    - craft\elements\Entry: 506
    - craft\elements\Asset: 439
    - verbb\navigation\elements\Node: 70
- Tracked Element Queries: 309
    - craft\elements\Entry: 297
    - verbb\navigation\elements\Node: 12
- Tracked Tags: 0

#### Site Tracking [#6]

- Tracked Pages: 210
- Tracked Includes: 20
- Tracked Query String Params: 0
- Tracked Elements: 913
    - craft\elements\Entry: 466
    - craft\elements\Asset: 387
    - verbb\navigation\elements\Node: 60
- Tracked Element Queries: 290
    - craft\elements\Entry: 279
    - verbb\navigation\elements\Node: 11
- Tracked Tags: 0

#### Site Tracking [#7]

- Tracked Pages: 643
- Tracked Includes: 28
- Tracked Query String Params: 0
- Tracked Elements: 1911
    - craft\elements\Asset: 945
    - craft\elements\Entry: 885
    - verbb\navigation\elements\Node: 81
- Tracked Element Queries: 723
    - craft\elements\Entry: 706
    - verbb\navigation\elements\Node: 17
- Tracked Tags: 0

#### Site Tracking [#8]

- Tracked Pages: 690
- Tracked Includes: 28
- Tracked Query String Params: 0
- Tracked Elements: 2088
    - craft\elements\Asset: 1,087
    - craft\elements\Entry: 919
    - verbb\navigation\elements\Node: 82
- Tracked Element Queries: 739
    - craft\elements\Entry: 722
    - verbb\navigation\elements\Node: 17
- Tracked Tags: 0

**Comment by bencroker** [comment] 2024-06-18 10:21
If that cache ID does not exist in the `blitz_caches` table, then no purge requests should be sent. How are you determining that the refresh is connected to the purges? And are you able to see what URL is being purged via CloudFront?

**Comment by jan-dh** [comment] 2024-06-18 10:29
We are seeing this in the queue log and the timestamps match the invalidation requests.

```
 "[2024-06-18 03:18:48] Blitz cache refresh job added : {"cacheIds":{"5585":true},"elements":[]} : [/app/modules/BlitzRefreshCacheLogger.php:25,/app/vendor/yiisoft/yii2/base/Component.php:633,/app/vendor/yiisoft/yii2-queue/src/Queue.php:194,/app/vendor/craftcms/cms/src/queue/Queue.php:260,/app/vendor/craftcms/cms/src/helpers/Queue.php:56,/app/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php:339,/app/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php:582,/app/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php:472,/app/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php:687,/app/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php:479,/app/vendor/putyourlightson/craft-blitz/src/Blitz.php:329,/app/vendor/yiisoft/yii2/base/Event.php:312,/app/vendor/yiisoft/yii2/base/Component.php:642,/app/vendor/craftcms/cms/src/base/ApplicationTrait.php:531,/app/vendor/craftcms/cms/src/base/ApplicationTrait.php:1661,/app/vendor/craftcms/cms/src/web/Application.php:110,/app/vendor/yiisoft/yii2/base/BaseObject.php:109,/app/vendor/yiisoft/yii2/base/Application.php:204,/app/vendor/yiisoft/yii2/di/Container.php:419,/app/vendor/yiisoft/yii2/di/Container.php:170,/app/vendor/yiisoft/yii2/BaseYii.php:365,/app/vendor/craftcms/cms/src/Craft.php:59,/app/vendor/craftcms/cms/bootstrap/bootstrap.php:264,/app/vendor/craftcms/cms/bootstrap/web.php:40,/app/web/index.php:16]"```

**Comment by bencroker** [comment] 2024-06-18 10:32
Are you able to see what URL is being purged via CloudFront?

**Comment by jan-dh** [comment] 2024-06-18 10:40
Going after the logs, don't have direct access myself

**Comment by jan-dh** [comment] 2024-06-18 11:38
Send through mail

**Comment by bencroker** [comment] 2024-06-18 11:48
Thanks. From what I can tell, the logs show lots of valid URLs being purged, so no particular clues there.

What I think is happening is that the cache ID `5585` exists when the refresh cache job is executed, but no longer exists when you visit the CP, presumably because the cached page has been regenerated and therefore assigned a new ID.

**Comment by jan-dh** [comment] 2024-06-18 11:51
The amount of invalidations with that missing cacheId in the DB (5585) from the server logs: `2,534` roughly matches the amount of validations of the homepage I find in the cloudfront logs: `2,537` (which is 3 more, which I manually triggered).

**Comment by jan-dh** [comment] 2024-06-18 11:57
I also see some invalidation requests very very close after eachother:
```
  {
    "eventTime": "2024-06-18T08:58:22Z",
    "items": [
      "/nl-be/"
    ]
  },
  {
    "eventTime": "2024-06-18T08:56:19Z",
    "items": [
      "/nl-be/"
    ]
  },
  {
    "eventTime": "2024-06-18T08:55:21Z",
    "items": [
      "/nl-be/"
    ]
  },
  {
    "eventTime": "2024-06-18T08:55:20Z",
    "items": [
      "/nl-be/"
    ]
  },
  {
    "eventTime": "2024-06-18T08:54:39Z",
    "items": [
      "/nl-be/"
    ]
  },
  ```
  So 5 invalidation requests for the same path within less than 4 seconds

**Comment by bencroker** [comment] 2024-06-18 12:01
> The amount of invalidations with that missing cacheId in the DB (5585) from the server logs: 2,534 roughly matches the amount of validations of the homepage I find in the cloudfront logs: 2,537 (which is 3 more, which I manually triggered).

So that looks like expected behaviour, nothing unusual there.

> So 5 invalidation requests for the same path within less than 4 seconds

Within 4 _minutes_, if I’m reading that correctly, which seems reasonable.

I can understand that you’re wondering why you’re getting so many invalidation requests, but there doesn’t appear to be any bug here, as far as I can tell.

**Comment by jan-dh** [comment] 2024-06-18 12:15
I'm struggling to see how 2.537k invalidation requests for an entry are "expected behaviour" if the entry itself is saved 3 times. Is there any way to get more insights as to what element could cause all these invalidations?

Correct about those 4 minutes, however again, the entry or linked elements were not resaved during that period of time.

**Comment by bencroker** [comment] 2024-06-18 12:28
> I'm struggling to see how 2.537k invalidation requests for an entry are "expected behaviour" if the entry itself is saved 3 times.

What I’m saying is that the number of invalidation requests appears to match the number of cache refreshes. As for why the homepage is refreshed so many times requires more digging. Would you able to log each time an element is saved, to help audit all content changes? I feel like that is the first step in understanding why the caches are being invalidated more often than you are expecting. You can adapt [this module](https://gist.github.com/bencroker/19b88e27a84496445d4f362522701c65) that I previously created for you, or let me know if you need help with it.

**Comment by jan-dh** [comment] 2024-06-18 12:56
If you would have some time to spare to help with it that would be greatly appreciated. Not sure what it is exactly we want to log here.

**Comment by bencroker** [comment] 2024-06-18 16:12
Here’s some code that will write to the Blitz log each time an element is added to the refresh data array. It can act as an audit for any time updated content is picked up by Blitz.

```php
use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\events\RefreshElementEvent;
use putyourlightson\blitz\services\RefreshCacheService;
use yii\base\Event;

Event::on(
    RefreshCacheService::class,
    RefreshCacheService::EVENT_AFTER_ADD_ELEMENT,
    function(RefreshElementEvent $event) {
        Blitz::$plugin->log('Element “' . $event->element->title . '” [' . $event->element->id . '] added to refresh data.');
    }
);
```

**Comment by jan-dh** [comment] 2024-06-18 19:37
Okido, added this to the code base & logs are coming in good. Only thing I'm wondering is if this would've been present before, you would just see 2.5K times "Home added to the refresh data"? I'm guessing we're looking for the actual element reason why it was added?

**Comment by bencroker** [comment] 2024-06-18 19:47
You can add whatever logging you want to help you get to the bottom of it. Look out for plugins or modules that can change content without human intervention, too (like Feed Me, for example, which appears to be installed).

**Comment by jan-dh** [comment] 2024-06-20 10:01
I tried adding detailed loggin to Matrix functionality but that gives performances issues.

**Comment by bencroker** [comment] 2024-06-20 12:02
It should only affect saves, not reads, but since matrix blocks cannot be saved independently of entries, I see no benefit to logging them.

**Comment by bencroker** [comment] 2024-06-27 10:02
Marking as closed, since I believe you have since found a workaround/solution.

**Closed as completed by bencroker** 2024-06-27 10:02 UTC
Labels: bug
