### ISSUE TITLE
RSS templates served with content-type text/html

### ISSUE THREAD

**Issue by roberttolton** [putyourlightson/craft-blitz#167] opened 2020-02-03 02:49 UTC
### Describe the bug
Per the Craft CMS 3 docs here: https://docs.craftcms.com/v3/dev/examples/rss-feed.html
You can create a `.rss` template that's used to create RSS feeds of content, with headers automatically applied.

However, Blitz caches these pages to, for example `/site/en/posts.rss/index.html`. This in itself isn't a problem, the fact that the RSS feeds get cache by Blitz is good in terms of speed, but the URLs are considered invalid RSS when 'served by Blitz' or NGINX.

I have tried the following NGINX rule to no avail, but for the times that things are 'served by Blitz' I'm not sure this rule would have any affect anyway.

```
location ^~ /en/posts.rss {
    types {}
    default_type application/rss+xml;
}
```

Apologies if this is something that _can_ be entirely fixed with NGINX / Apache rules, but what I have been trying hasn't worked, so for now I've had to exclude `.rss` in Blitz's settings and rely on Craft's `{% cache %}` tag.

### To reproduce
Steps to reproduce the behaviour:
1. Install Craft & Blitz
2. Create Entries
3. Create `posts.rss` template
4. Load `mysite.com/posts.rss`

### Expected behaviour
Page should be cached and served with `application/rss+xml` content-type.

### Versions
- Plugin version: 3.1.1
- Craft version: 3.3.20.1

**Comment by bencroker** [comment] 2020-02-03 06:30
Added better handling of file extensions in https://github.com/putyourlightson/craft-blitz/commit/8577e3f298f219ddd5a0a6774b81ef8bd81b5754, which should solve it for you when cached pages are served by Blitz. You can test this with the `develop` branch:
```
composer require putyourlightson/craft-blitz:dev-develop
```

To make this work with server redirects, you'll have to figure out a way to specify it in the Nginx config. Perhaps this will work?
```
location /en/posts.rss {
    types {}
    default_type application/rss+xml;
}
```

**Comment by roberttolton** [comment] 2020-02-04 00:34
Thanks @bencroker that fix solves the issue for serving by Blitz, however I had to make the Nginx rule as follows:
```
location /en/posts.rss {
        types {}
        default_type application/rss+xml;
        try_files /cache/blitz/$http_host${request_uri}/index.html /cache/blitz/$http_host${request_uri}index.html $uri $uri/ /index.php?$query_string;
}
```
Basically adding the `try_files` statement, otherwise it just seemed not to work. Don't know if this is correct or not.

Also, when I tried saving an entry that kicked-off some cache warming tasks, they all failed with:
```
Argument 1 passed to craft\helpers\UrlHelper::siteUrl() must be of the type string, null given, called in /home/forge/site.com/vendor/putyourlightson/craft-blitz/src/models/SiteUriModel.php on line 37
```

The payload being:
```
{
    "cacheIds": [],
    "elements": {
        "myplugin\\example\\elements\\Post": {
            "elementIds": [
                30967,
                30968,
                30969
            ],
            "sourceIds": []
        },
        "craft\\elements\\Entry": {
            "elementIds": [
                30966
            ],
            "sourceIds": [
                "1"
            ]
        }
    },
    "clearCache": true,
    "description": null
}
```

**Comment by bencroker** [comment] 2020-02-04 09:40
Ok great, looks like you solved it with that Nginx rule.

That second issue is unrelated, but was being caused by an issue on the `develop` branch.
Fixed in https://github.com/putyourlightson/craft-blitz/commit/14df03b3679cb46ae0f94135504f87cfeb84cc8f.

**Comment by bencroker** [comment] 2020-02-04 17:30
Added in 3.2.0

**Closed as completed by bencroker** 2020-02-04 17:30 UTC
Labels: bug
