### ISSUE TITLE
Compatibility issue with ostark/craft-relax: Queue must be an application component.

### ISSUE THREAD

**Issue by lukasNo1** [putyourlightson/craft-blitz#591] opened 2023-11-30 13:07 UTC
I just update from 4.5.3 to 4.9.3 and now i receive this error every time i try to save a cached site in the cms.

I reverted the update and it worked again.

`Queue must be an application component. {"trace":["#0 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(836): craft\\queue\\Queue->componentId()","#1 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(645): craft\\queue\\Queue->channel()","#2 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2-queue/src/Queue.php(193): craft\\queue\\Queue->pushMessage('O:42:\"putyourli...', 300, 0, 10)","#3 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php(259): yii\\queue\\Queue->push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob))","#4 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/helpers/Queue.php(56): craft\\queue\\Queue->push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob))","#5 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(344): craft\\helpers\\Queue::push(Object(putyourlightson\\blitz\\jobs\\RefreshCacheJob), 10, NULL, NULL, Object(craft\\queue\\Queue))","#6 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php(254): putyourlightson\\blitz\\services\\RefreshCacheService->refresh()","#7 /var/www/vhosts/project/project/current/backend/vendor/putyourlightson/craft-blitz/src/Blitz.php(384): putyourlightson\\blitz\\services\\RefreshCacheService->addElement(Object(craft\\elements\\Entry))","#8 [internal function]: putyourlightson\\blitz\\Blitz->putyourlightson\\blitz\\{closure}(Object(craft\\events\\ElementEvent))","#9 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\\events\\ElementEvent))","#10 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Component.php(642): yii\\base\\Event::trigger('craft\\\\services\\\\...', 'afterSaveElemen...', Object(craft\\events\\ElementEvent))","#11 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(3533): yii\\base\\Component->trigger('afterSaveElemen...', Object(craft\\events\\ElementEvent))","#12 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(1615): craft\\services\\Elements->_saveElementInternal(Object(craft\\elements\\Entry), false, false, true, Array)","#13 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Elements.php(1261): craft\\services\\Elements->duplicateElement(Object(craft\\elements\\Entry), Array)","#14 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/services/Drafts.php(305): craft\\services\\Elements->updateCanonicalElement(Object(craft\\elements\\Entry), Array)","#15 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/controllers/ElementsController.php(1550): craft\\services\\Drafts->applyDraft(Object(craft\\elements\\Entry))","#16 [internal function]: craft\\controllers\\ElementsController->actionApplyDraft()","#17 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#18 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#19 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('apply-draft', Array)","#20 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(305): yii\\base\\Module->runAction('elements/apply-...', Array)","#21 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(606): craft\\web\\Application->runAction('elements/apply-...', Array)","#22 /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/web/Application.php(284): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))","#23 /var/www/vhosts/project/project/current/backend/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","#24 /var/www/vhosts/project/project/current/public/index.php(14): yii\\base\\Application->run()","#25 {main}"],"memory":8547704,"exception":"[object] (yii\\base\\InvalidConfigException(code: 0): Queue must be an application component. at /var/www/vhosts/project/project/current/backend/vendor/craftcms/cms/src/queue/Queue.php:695)"}`

Blitz config is this if it matters:
```
  '*'     => [
        'cacheStorageSettings'    => [
            'folderPath' => '@basePath/../public/cache/blitz',
        ],
        'cachingEnabled'          => true,
        'clearCacheAutomatically' => true,
        'warmCacheAutomatically'  => false,
        'queryStringCaching'      => 1,
        'cacheDuration'           => 0,
        'includedUriPatterns'     => [
            [
                'siteId'     => '',
                'uriPattern' => '.*',
            ],
        ],
        'excludedUriPatterns'     => [],
    ],
    'local' => [
        'cachingEnabled' => (bool)getenv('FULLPAGE_CACHE'),
    ],
```

**Comment by lukasNo1** [comment] 2023-11-30 13:27
It seems to be a problem with ostark/craft-relax (2.0.1)
When i deactivate relax, blitz 4.9.3 works.
Maybe something @ostark needs to fix.

**Comment by ostark** [comment] 2023-11-30 14:13
Probably this
https://github.com/putyourlightson/craft-blitz/issues/577#issuecomment-1812107829

**Comment by bencroker** [comment] 2023-11-30 15:23
> Probably this [#577 (comment)](https://github.com/putyourlightson/craft-blitz/issues/577#issuecomment-1812107829)

@ostark right, but that’s a pattern that Feed Me employs too. You’ve added “extrawurst” to make it work in the `QueueServiceHandler`, perhaps you can find a more generic solution?
https://github.com/ostark/craft-relax/blob/4dd1c066b8b30d2da8fc097c93d0c6716ab531d4/src/Handlers/QueueServiceHandler.php#L47-L51

**Comment by ostark** [comment] 2023-11-30 16:01
Extrawurst is the worst. I'll have a look.

**Comment by bencroker** [comment] 2023-12-17 16:18
Any update on this, @ostark?

**Comment by bencroker** [comment] 2023-12-20 01:28
Closing this issue in favour of https://github.com/ostark/craft-relax/issues/16.

**Closed as completed by bencroker** 2023-12-20 01:28 UTC
Labels: bug

**Comment by ostark** [comment] 2023-12-20 06:41
Did you change anything?

**Comment by bencroker** [comment] 2023-12-20 13:05
Nope, the issue is on you unless you tell me otherwise.

**Comment by ostark** [comment] 2024-01-04 12:56
Extrawurst added 

https://github.com/ostark/craft-relax/blob/main/src/Handlers/QueueServiceHandler.php#L54-L59

**Comment by bencroker** [comment] 2024-01-04 13:22
Thanks @ostark. I have two other plugins that need Extrawurst, so a long-term solution would be desirable.

**Comment by ostark** [comment] 2024-01-04 13:48
I could fire an Event you can listen to.
Honestly, I've no idea what this `$queue` properly on your main class does.

**Comment by bencroker** [comment] 2024-01-04 14:43
> Honestly, I've no idea what this $queue properly on your main class does.

It is a custom queue component, so that the plugin’s jobs can be run via a custom queue. This functionality was added in Craft 3.4 and Feed Me 4.4.3.

See https://github.com/craftcms/cms/issues/5492
